project_id = "ypnciiargbltekencinc"

[functions.ai-chat]
verify_jwt = false

[functions.badge-checker]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.session-notification-trigger]
verify_jwt = false

[functions.update-attendance-patterns]
verify_jwt = false